class Actions {
  static const GET_DOCTORS_LIST_REQ = "GET_DOCTORS_LIST_REQ";
  static const GET_DOCTORS_LIST_SUCCESS = "GET_DOCTORS_LIST_SUCCESS";
  static const GET_DOCTORS_LIST_FAILED = "GET_DOCTORS_LIST_FAILED";
  static const GET_REVIEWS_REQ = "GET_REVIEWS_REQ";
  static const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
  static const GET_REVIEWS_FAILED = "GET_REVIEWS_FAILED";
}
